name: Update Release with Jar

on:
  push:
    branches:
      - 'main'

jobs:
  update-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create or Update Release
      id: create_or_update_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0  # Dein Release-Tag hier
        release_name: Release v1.0  # Der Name deines Releases
        body: New Release
        draft: false
        prerelease: false
    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_or_update_release.outputs.upload_url }}
        asset_path: ./target/your-project.jar
        asset_name: your-project.jar
        asset_content_type: application/java-archive
