name: Java CI with Maven

on:
  push:
    branches:
      - 'master'
      - 'feature/*'  # Reagiere auch auf Änderungen in Feature-Branches
  pull_request:
    branches:
      - 'master'
      - 'feature/*'  # Reagiere auch auf Pull-Requests von Feature-Branches
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    # Hochladen der JAR-Datei zu GitHub Releases
    - name: Upload JAR to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: ./target/your-project.jar
        asset_name: your-project.jar
        asset_content_type: application/java-archive
