name: Java CI with Maven

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload .jar file
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/*.jar  # Verwende den Pfad zur .jar-Datei
        asset_name: your-project.jar
        asset_content_type: application/java-archive
        token: ${{ secrets.GITHUB_TOKEN }}
