name: Test Feature Branches

on:
  push:
    branches:
      - 'feature/*'  # Reagiere nur auf Änderungen in Feature-Branches

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'  # oder 'temurin' je nach Ihrem Bedarf

    - name: Build and test
      run: |
        mvn clean install  # Anpassen an Ihre Bedürfnisse
        mvn test  # Anpassen an Ihre Bedürfnisse
