name: Upload JAR on Main Branch Merge

on:
  push:
    branches:
      - 'master'

jobs:
  upload-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build JAR
        run: mvn clean package

      - name: Upload JAR to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ./target/*.jar
          asset_name: example.jar
          asset_content_type: application/java-archive
          token: ${{ secrets.GITHUB_TOKEN }}
